apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app1
    env: test
    version: v1
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  replicas: 3
  selector:
    matchLabels:
      app: app1
      env: test
  template:
    metadata:
      labels:
        app: app1
        env: test
        version: v1
    spec:
      containers:
      - name: app1
        image: hscrystal/app1:4.0.0
        ports:
        - containerPort: 80
        startupProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  selector:
    app: app1
  ports:
  - name: http
    port: 80
    targetPort: 80