name: Docker Image CI

on:
  push:
    tags:
      - 'v*' # แนะนำให้ใช้ v* เพื่อกรองเฉพาะ Version tags
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      image_tag: ${{ steps.meta.outputs.version }} # ส่งออก Tag ไปใช้ต่อ
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=short

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          
  vulnerability:
    needs: build
    if: github.event_name != 'pull_request' # รันเฉพาะตอน Push Tag จริงเท่านั้น
    runs-on: ubuntu-24.04
    steps:
      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}:${{ needs.build.outputs.image_tag }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

  modifygit:
    needs: [build, vulnerability]
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ secrets.GIT_REPO }}
          token: ${{ secrets.GIT_TOKEN }}
          ref: main

      - name: modify the image tag
        run: |
          git config user.email ${{ secrets.EMAIL }}
          git config user.name ${{ secrets.GIT_USERNAME }}
          # ใช้ตัวแปรเดียวกับที่ Build
          sed -i "s|${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}:.*|${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}:${{ needs.build.outputs.image_tag }}|g" manifest/deployment.yaml
          git add .
          git commit -m 'Update image to ${{ needs.build.outputs.image_tag }}'
          git push
